package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAY_AFTER_BAC".
 */
public class DayAfterBAC {

    private Long id;
    private java.util.Date timestamp;
    private String unit;

    public DayAfterBAC() {
    }

    public DayAfterBAC(Long id) {
        this.id = id;
    }

    public DayAfterBAC(Long id, java.util.Date timestamp, String unit) {
        this.id = id;
        this.timestamp = timestamp;
        this.unit = unit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

}
