package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GRAPH_HISTORY".
 */
public class GraphHistory {

    private Long id;
    private Double currentBAC;
    private java.util.Date timestamp;
    private long historyId;

    public GraphHistory() {
    }

    public GraphHistory(Long id) {
        this.id = id;
    }

    public GraphHistory(Long id, Double currentBAC, java.util.Date timestamp, long historyId) {
        this.id = id;
        this.currentBAC = currentBAC;
        this.timestamp = timestamp;
        this.historyId = historyId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getCurrentBAC() {
        return currentBAC;
    }

    public void setCurrentBAC(Double currentBAC) {
        this.currentBAC = currentBAC;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

    public long getHistoryId() {
        return historyId;
    }

    public void setHistoryId(long historyId) {
        this.historyId = historyId;
    }

}
