package rustelefonen.no.drikkevett_android.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import rustelefonen.no.drikkevett_android.db.GraphHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRAPH_HISTORY".
*/
public class GraphHistoryDao extends AbstractDao<GraphHistory, Long> {

    public static final String TABLENAME = "GRAPH_HISTORY";

    /**
     * Properties of entity GraphHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CurrentBAC = new Property(1, Double.class, "currentBAC", false, "CURRENT_BAC");
        public final static Property Timestamp = new Property(2, java.util.Date.class, "timestamp", false, "TIMESTAMP");
        public final static Property HistoryId = new Property(3, long.class, "historyId", false, "HISTORY_ID");
    };

    private Query<GraphHistory> history_GraphHistoriesQuery;

    public GraphHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public GraphHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRAPH_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CURRENT_BAC\" REAL," + // 1: currentBAC
                "\"TIMESTAMP\" INTEGER," + // 2: timestamp
                "\"HISTORY_ID\" INTEGER NOT NULL );"); // 3: historyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRAPH_HISTORY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GraphHistory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double currentBAC = entity.getCurrentBAC();
        if (currentBAC != null) {
            stmt.bindDouble(2, currentBAC);
        }
 
        java.util.Date timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(3, timestamp.getTime());
        }
        stmt.bindLong(4, entity.getHistoryId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GraphHistory readEntity(Cursor cursor, int offset) {
        GraphHistory entity = new GraphHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // currentBAC
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // timestamp
            cursor.getLong(offset + 3) // historyId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GraphHistory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurrentBAC(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setTimestamp(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setHistoryId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GraphHistory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GraphHistory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "graphHistories" to-many relationship of History. */
    public List<GraphHistory> _queryHistory_GraphHistories(long historyId) {
        synchronized (this) {
            if (history_GraphHistoriesQuery == null) {
                QueryBuilder<GraphHistory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.HistoryId.eq(null));
                history_GraphHistoriesQuery = queryBuilder.build();
            }
        }
        Query<GraphHistory> query = history_GraphHistoriesQuery.forCurrentThread();
        query.setParameter(0, historyId);
        return query.list();
    }

}
