package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INFORMATION".
 */
public class Information implements java.io.Serializable {

    private Long id;
    private String name;
    private String content;
    private byte[] image;
    private long categoryId;

    public Information() {
    }

    public Information(Long id) {
        this.id = id;
    }

    public Information(Long id, String name, String content, byte[] image, long categoryId) {
        this.id = id;
        this.name = name;
        this.content = content;
        this.image = image;
        this.categoryId = categoryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

}
