package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAN_PARTY_ELEMENTS".
 */
public class PlanPartyElements {

    private Long id;
    private String status;
    private Integer plannedBeer;
    private Integer plannedWine;
    private Integer plannedDrink;
    private Integer plannedShot;
    private Integer aftRegBeer;
    private Integer aftRegWine;
    private Integer aftRegDrink;
    private Integer aftRegShot;
    private java.util.Date firstUnitAddedDate;
    private java.util.Date startTimeStamp;
    private java.util.Date endTimeStamp;

    public PlanPartyElements() {
    }

    public PlanPartyElements(Long id) {
        this.id = id;
    }

    public PlanPartyElements(Long id, String status, Integer plannedBeer, Integer plannedWine, Integer plannedDrink, Integer plannedShot, Integer aftRegBeer, Integer aftRegWine, Integer aftRegDrink, Integer aftRegShot, java.util.Date firstUnitAddedDate, java.util.Date startTimeStamp, java.util.Date endTimeStamp) {
        this.id = id;
        this.status = status;
        this.plannedBeer = plannedBeer;
        this.plannedWine = plannedWine;
        this.plannedDrink = plannedDrink;
        this.plannedShot = plannedShot;
        this.aftRegBeer = aftRegBeer;
        this.aftRegWine = aftRegWine;
        this.aftRegDrink = aftRegDrink;
        this.aftRegShot = aftRegShot;
        this.firstUnitAddedDate = firstUnitAddedDate;
        this.startTimeStamp = startTimeStamp;
        this.endTimeStamp = endTimeStamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getPlannedBeer() {
        return plannedBeer;
    }

    public void setPlannedBeer(Integer plannedBeer) {
        this.plannedBeer = plannedBeer;
    }

    public Integer getPlannedWine() {
        return plannedWine;
    }

    public void setPlannedWine(Integer plannedWine) {
        this.plannedWine = plannedWine;
    }

    public Integer getPlannedDrink() {
        return plannedDrink;
    }

    public void setPlannedDrink(Integer plannedDrink) {
        this.plannedDrink = plannedDrink;
    }

    public Integer getPlannedShot() {
        return plannedShot;
    }

    public void setPlannedShot(Integer plannedShot) {
        this.plannedShot = plannedShot;
    }

    public Integer getAftRegBeer() {
        return aftRegBeer;
    }

    public void setAftRegBeer(Integer aftRegBeer) {
        this.aftRegBeer = aftRegBeer;
    }

    public Integer getAftRegWine() {
        return aftRegWine;
    }

    public void setAftRegWine(Integer aftRegWine) {
        this.aftRegWine = aftRegWine;
    }

    public Integer getAftRegDrink() {
        return aftRegDrink;
    }

    public void setAftRegDrink(Integer aftRegDrink) {
        this.aftRegDrink = aftRegDrink;
    }

    public Integer getAftRegShot() {
        return aftRegShot;
    }

    public void setAftRegShot(Integer aftRegShot) {
        this.aftRegShot = aftRegShot;
    }

    public java.util.Date getFirstUnitAddedDate() {
        return firstUnitAddedDate;
    }

    public void setFirstUnitAddedDate(java.util.Date firstUnitAddedDate) {
        this.firstUnitAddedDate = firstUnitAddedDate;
    }

    public java.util.Date getStartTimeStamp() {
        return startTimeStamp;
    }

    public void setStartTimeStamp(java.util.Date startTimeStamp) {
        this.startTimeStamp = startTimeStamp;
    }

    public java.util.Date getEndTimeStamp() {
        return endTimeStamp;
    }

    public void setEndTimeStamp(java.util.Date endTimeStamp) {
        this.endTimeStamp = endTimeStamp;
    }

}
