package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAN_PARTY_ELEMENTS".
 */
public class PlanPartyElements {

    private String status;
    private Integer plannedBeer;
    private Integer plannedWine;
    private Integer plannedDrink;
    private Integer plannedShot;

    public PlanPartyElements() {
    }

    public PlanPartyElements(String status, Integer plannedBeer, Integer plannedWine, Integer plannedDrink, Integer plannedShot) {
        this.status = status;
        this.plannedBeer = plannedBeer;
        this.plannedWine = plannedWine;
        this.plannedDrink = plannedDrink;
        this.plannedShot = plannedShot;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getPlannedBeer() {
        return plannedBeer;
    }

    public void setPlannedBeer(Integer plannedBeer) {
        this.plannedBeer = plannedBeer;
    }

    public Integer getPlannedWine() {
        return plannedWine;
    }

    public void setPlannedWine(Integer plannedWine) {
        this.plannedWine = plannedWine;
    }

    public Integer getPlannedDrink() {
        return plannedDrink;
    }

    public void setPlannedDrink(Integer plannedDrink) {
        this.plannedDrink = plannedDrink;
    }

    public Integer getPlannedShot() {
        return plannedShot;
    }

    public void setPlannedShot(Integer plannedShot) {
        this.plannedShot = plannedShot;
    }

}
