package rustelefonen.no.drikkevett_android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User implements java.io.Serializable {

    private Long id;
    private Integer age;
    private Integer beerPrice;
    private Integer winePrice;
    private Integer drinkPrice;
    private Integer shotPrice;
    private String gender;
    private java.util.Date goalDate;
    private Double goalBAC;
    private String nickname;
    private Double weight;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer age, Integer beerPrice, Integer winePrice, Integer drinkPrice, Integer shotPrice, String gender, java.util.Date goalDate, Double goalBAC, String nickname, Double weight) {
        this.id = id;
        this.age = age;
        this.beerPrice = beerPrice;
        this.winePrice = winePrice;
        this.drinkPrice = drinkPrice;
        this.shotPrice = shotPrice;
        this.gender = gender;
        this.goalDate = goalDate;
        this.goalBAC = goalBAC;
        this.nickname = nickname;
        this.weight = weight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getBeerPrice() {
        return beerPrice;
    }

    public void setBeerPrice(Integer beerPrice) {
        this.beerPrice = beerPrice;
    }

    public Integer getWinePrice() {
        return winePrice;
    }

    public void setWinePrice(Integer winePrice) {
        this.winePrice = winePrice;
    }

    public Integer getDrinkPrice() {
        return drinkPrice;
    }

    public void setDrinkPrice(Integer drinkPrice) {
        this.drinkPrice = drinkPrice;
    }

    public Integer getShotPrice() {
        return shotPrice;
    }

    public void setShotPrice(Integer shotPrice) {
        this.shotPrice = shotPrice;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public java.util.Date getGoalDate() {
        return goalDate;
    }

    public void setGoalDate(java.util.Date goalDate) {
        this.goalDate = goalDate;
    }

    public Double getGoalBAC() {
        return goalBAC;
    }

    public void setGoalBAC(Double goalBAC) {
        this.goalBAC = goalBAC;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

}
